/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dlam' at '1/28/17 2:49 PM' with Gradle 3.0
 *
 * @author dlam, @date 1/28/17 2:49 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
